M48
; DRILL file {KiCad (6.0.7)} date Mon Oct 31 09:28:41 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-10-31T09:28:41+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X54.0Y-54.0
X54.0Y-106.0
X70.145Y-101.0
X125.755Y-101.0
X141.0Y-54.0
X141.0Y-106.0
T0
M30
